version: '3.5'

services:
  spark-master:
    env_file:
      - spark_master_env
    hostname: spark-master
    image: fhuertas/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    env_file:
      - spark_worker_env
    hostname: spark-worker-1
    image: fhuertas/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      SPARK_WORKER_WEBUI_PORT: "30081"
    ports:
      - "30081:30081"
  spark-worker-2:
    env_file:
      - spark_worker_env
    hostname: spark-worker-2
    image: fhuertas/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      SPARK_WORKER_WEBUI_PORT: "20081"
    ports:
      - "20081:20081"
